/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rh_Searcher */
#include <jvmti.h>

#ifndef _Included_rh_Searcher
#define _Included_rh_Searcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rh_Searcher
 * Method:    findAll
 * Signature: (Ljava/lang/Class;)Ljava/util/Collection;
 */
JNIEXPORT jobject JNICALL Java_rh_Searcher_findAll
(JNIEnv*, jclass, jclass);

/*
 * Class:     rh_Searcher
 * Method:    printLn
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rh_Searcher_printLn
(JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
